### ISSUE TITLE
File input not working

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/aix#46]
It looks like file input isn't working.

**Works:**

`aix -p "Write a haiku`

<img width="639" alt="CleanShot 2023-05-19 at 09 20 05@2x" src="https://github.com/projectdiscovery/aix/assets/6044920/8027db18-daf8-41aa-829b-cc3dd3172763">

**Doesn't work:**

- `cat ./aiinput`
- `Write a haiku`

<img width="358" alt="CleanShot 2023-05-19 at 09 20 32@2x" src="https://github.com/projectdiscovery/aix/assets/6044920/bcd528c0-993a-4176-91be-cf183752385c">

- `aix -p ./aiinput`
- Error:

<img width="1428" alt="CleanShot 2023-05-19 at 09 19 35@2x" src="https://github.com/projectdiscovery/aix/assets/6044920/49e2cc9d-c82e-4047-b3dd-847400e24ffc">

**Comment by ehsandeep** [comment]
@olearycrew this is now fixed with latest release - https://github.com/projectdiscovery/aix/releases/tag/v0.0.3
